---
title: "age_focused_data"
output: html_document
---

```{r setup, echo=FALSE, message=FALSE, warning=FALSE}

library(showtext)
library(glptools)
glp_load_packages(T)

knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, cache = FALSE,  
                      dev.args=list(bg="transparent"), fig.width=9, fig.height=6) 

```

```{r clean_data, eval = FALSE}
load("C:/Users/morga/OneDrive - The Community Foundation of Louisville, Inc/acs_micro_subset.RData")

disability_data_age <- disability_data

disability_data_age %<>%
  mutate(
    # Ambulatory difficulty
    dis_physical = case_when(
      DIFFPHYS == 0 ~ NA, #tilde indicates formula
      DIFFPHYS == 1 ~ F,
      DIFFPHYS == 2 ~ T),
    
    # Independent living difficulty
    dis_independent = case_when(
      DIFFMOB == 0 ~ NA,
      DIFFMOB == 1 ~ F,
      DIFFMOB == 2 ~ T), 
    
    # Self-care difficulty
    dis_selfcare  = case_when(
      DIFFCARE  == 0 ~ NA,
      DIFFCARE  == 1 ~ F,
      DIFFCARE  == 2 ~ T), 
    
    # Vision difficulty
    dis_vision = case_when(
      DIFFEYE == 0 ~ NA,
      DIFFEYE == 1 ~ F,
      DIFFEYE == 2 ~ T), 
    
    # Hearing difficulty
    dis_hearing  = case_when(
      DIFFHEAR  == 0 ~ NA,
      DIFFHEAR  == 1 ~ F,
      DIFFHEAR  == 2 ~ T),
    
    dis_any = if_else((dis_physical + dis_independent + dis_selfcare + dis_vision + dis_hearing) > 0, T, F),
    

    age_group_5yr = case_when(
      age %in% 50:54 ~ "50-54",
      age %in% 55:59 ~ "55-59",
      age %in% 60:64 ~ "60-64",
      age %in% 65:69 ~ "65-69",
      age %in% 70:74 ~ "70-74",
      age %in% 75:79 ~ "75-79",
      age %in% 80:84 ~ "80-84",
      age >= 85 ~ "85+"), 

    age_group_10yr = case_when(
      age %in% 50:64 ~ "50-64",
      age %in% 65:74 ~ "65-74",
      age %in% 75:84 ~ "75-84",
      age >= 85 ~ "85+"), 
    

    HHINCOME = replace(HHINCOME, HHINCOME == 99999, NA),
  
    income_group = case_when(
      HHINCOME < 20000 ~ "Under 20k",
      HHINCOME >= 20000 & HHINCOME < 50000 ~ "20k–49.9k",
      HHINCOME >= 50000 & HHINCOME < 75000 ~ "50k–74.9k",
      HHINCOME >= 75000 & HHINCOME < 100000 ~ "75k–99.9k",
      HHINCOME >= 100000 & HHINCOME < 150000 ~ "100k–149.9k",
      HHINCOME >= 150000 ~ "150k+",
      TRUE ~ NA_character_  ),  # catch-all for missing/unspecified values, "TRUE" could also be "is.na(HHICOME)"
  
  # Homeownership- Not sure if we'll use them all. Rent vs. own for sure, unsure about others.
  
    OWNCOST  = replace(OWNCOST, OWNCOST == 99999, NA),
    OWNERSHP = replace(OWNERSHP, OWNERSHP == 0, NA),
    RENTGRS  = replace(RENTGRS, RENTGRS == 0 & OWNERSHP == 1, NA),

    homeownership = if_else(OWNERSHP == 1, T, F),

    hcost = if_else(homeownership == 1, OWNCOST, RENTGRS),
    cost_burden = if_else(hcost * 12 / HHINCOME > 0.3, T, F),
    severe_cost_burden = if_else(hcost * 12 / HHINCOME > 0.5, 1, 0),

    hh_type = case_when(
      homeownership  & !cost_burden ~ "noncb_homeowner",
      homeownership  & cost_burden  ~ "cb_homeowner",
      !homeownership & !cost_burden ~ "noncb_renter",
      !homeownership & cost_burden  ~ "cb_renter",
      TRUE ~ NA_character_)
    
    )

# MB Checking the disability variable recode. The colon selects several columns. Nifty!
# disability_data[1:100,] %>% select(dis_physical:dis_any)


## HOUSEHOLD
# @Morgan this makes a variable that flags whether anyone in the household (HH) has a disability!!

disability_data_age %<>%
  
  #@MB HHs are identified by unique values of SERIAL. (SERIAL is repeated across years, hence the need to group by year as well)
  group_by(year, SERIAL) %>% 
  
  #@MB back to vectorized! The verb any is looking up and down the small subset of observations we have created for each HH via group_by to see if dis_physical is true in any of the rows. This type of operation usually takes way longer than simple row-wise operations, so this code is suuuuuper slow.
  
  mutate(
    any_dis_physical    = if_else(any(dis_physical), T, F), 
    any_dis_independent = if_else(any(dis_independent), T, F),
    any_dis_selfcare    = if_else(any(dis_selfcare), T, F),
    any_dis_vision      = if_else(any(dis_vision), T, F),
    any_dis_hearing     = if_else(any(dis_hearing), T, F),
    any_dis_any         = if_else(any(dis_any), T, F)) %>% #@MB lol at this naming convention :)
  ungroup() 

#@MB saving 
arrow::write_feather(disability_data_age, "interim_data/disability_data_age.feather")

```

```{r create_age_table, eval = FALSE}
individual_dis_age_4 <- survey_by_demog(disability_data_age, 
                                        "dis_physical", 
                                        "PERWT", 
                                        other_grouping_vars = "age_group_5yr")
group_var <-  "age_group_5yr"

age_and_physical <- survey_by_demog(disability_data_age, "dis_physical", "PERWT", 
                                    other_grouping_vars = group_var)
age_and_independent <- survey_by_demog(disability_data_age, "dis_independent", "PERWT",
                                       other_grouping_vars = group_var)
age_and_selfcare <- survey_by_demog(disability_data_age, "dis_selfcare", "PERWT", 
                                    other_grouping_vars = group_var)
age_and_vision <- survey_by_demog(disability_data_age, "dis_vision", "PERWT", 
                                  other_grouping_vars = group_var)
age_and_hearing <- survey_by_demog(disability_data_age, "dis_hearing", "PERWT", 
                                   other_grouping_vars = group_var)
age_and_any <- survey_by_demog(disability_data_age, "dis_any", "PERWT",  
                               other_grouping_vars = group_var)

age_all_5yr <- age_and_hearing %>%
  left_join(age_and_independent, by = c("FIPS","year","sex","race","var_type", group_var)) %>%
  left_join(age_and_physical,   by = c("FIPS","year","sex","race","var_type", group_var)) %>%
  left_join(age_and_vision,     by = c("FIPS","year","sex","race","var_type", group_var)) %>%
  left_join(age_and_any,        by = c("FIPS","year","sex","race","var_type", group_var)) %>%
  left_join(age_and_selfcare,   by = c("FIPS","year","sex","race","var_type", group_var))

#factorize so legend is ordered
age_levels <- c("50-54", "55-59", "60-64","65-69", "70-74", "75-79","80-84", "85 or Older")

age_all_5yr <- age_all_5yr %>%
  mutate(age_group_5yr = factor(age_group_5yr, levels = age_levels, ordered = TRUE))

rm(age_and_any, age_and_hearing, age_and_independent, age_and_physical, age_and_selfcare, age_and_vision)

save(age_all_5yr, file = "interim_data/age_5yr_all_dis.RData")
```

```{r age_chart}
load(file = "interim_data/age_5yr_all_dis.RData")
showtext_auto()
colors <- colorRampPalette(c("#FFCCC2", "#cc3f14"))(8)

#clean table
dis_by_age <- age_all %>%
  filter(year == 2023, sex == "total", race == "total", var_type == "percent",!is.na(age_group_5yr)) %>%
  pivot_longer(cols = c(dis_physical, dis_independent, dis_selfcare, dis_vision, dis_hearing, dis_any),
               names_to = "Disability_Type", 
               values_to = "Percent") %>% 
  mutate(Disability_Type = recode(Disability_Type, dis_physical = "Physical",
                                  dis_independent = "Ind. Living",
                                  dis_selfcare = "Self-Care",
                                  dis_vision = "Vision",
                                  dis_hearing = "Hearing",
                                  dis_any = "Any")) %>%
  select(age_group_5yr, Disability_Type, Percent) %>% 
  rename(Age = age_group_5yr)

plot5yr <- ggplot(dis_by_age, aes(x = Disability_Type, y = Percent, fill = Age)) +  # fill says split x category by this category
  geom_col(position = position_dodge(width = 0.5), width = 0.5) + #dodge = side by side not stacked 
  labs(
    title = "Disabilities Breakdown by Age- 50+ (2023)",
    x = NULL, y = "Percent of Population"
  ) +
  scale_fill_manual(values = colors) +  
 theme_minimal(base_family = "Montserrat", base_size = 22) +
  theme(
    axis.text.x = element_text(angle = 30, hjust = 1, family = "Montserrat"),
    plot.title = element_text(face = "bold", size = 26, family = "Montserrat")
  )

  ggsave("interim_data/plots/dis_by_age_5yr.png", plot= plot5yr)
  print(plot5yr)
```